import random
import turtle

t = turtle.Turtle()
t.color(random.choice(['black', 'red', 'orange', 'yellow', 'green', 'blue', 'purple', 'white']))
t.forward(64)
t.left(45)
t.color(random.choice(['black', 'red', 'orange', 'yellow', 'green', 'blue', 'purple', 'white']))
t.forward(64)
t.left(45)
t.color(random.choice(['black', 'red', 'orange', 'yellow', 'green', 'blue', 'purple', 'white']))
t.forward(64)
t.left(45)
t.color(random.choice(['black', 'red', 'orange', 'yellow', 'green', 'blue', 'purple', 'white']))
t.forward(64)
t.left(45)
t.color(random.choice(['black', 'red', 'orange', 'yellow', 'green', 'blue', 'purple', 'white']))
t.forward(64)
t.left(45)
t.color(random.choice(['black', 'red', 'orange', 'yellow', 'green', 'blue', 'purple', 'white']))
t.forward(64)
t.left(45)
t.color(random.choice(['black', 'red', 'orange', 'yellow', 'green', 'blue', 'purple', 'white']))
t.forward(64)
t.left(45)
t.color(random.choice(['black', 'red', 'orange', 'yellow', 'green', 'blue', 'purple', 'white']))
t.forward(64)
t.left(45)

print(dir(t))
